### ISSUE TITLE
和XVim兼容不好，希望能改进

### ISSUE THREAD

**Issue by zld** [keepyounger/HighlightSelectedString#1]
可能XVim开启下，双击选择后的模式不一样？效果如下
![qq20150205-1 2x](https://cloud.githubusercontent.com/assets/2616502/6054618/b9abb0ae-ad2a-11e4-8c55-075b20eb6653.png)

**Comment by keepyounger** [comment]
@zld 已修正

**Comment by zld** [comment]
好效率，赞👍
