### ISSUE TITLE
Doesn't work with Xcode 7.2 beta (7C46l)

### ISSUE THREAD

**Issue by MarcVienna** [keepyounger/HighlightSelectedString#11]
Works fine with Xcode 7.1 (7B91b)
Doesn't work with Xcode 7.2 beta (7C46l) - when you launch Xcode-beta it doesn't ask whether to load the bundle, and thus doesn't load it.

**Comment by keepyounger** [comment]
You can download my project [AutoAddUUID](https://github.com/keepyounger/AutoAddUUID) to solve this issue.
1.download  [AutoAddUUID](https://github.com/keepyounger/AutoAddUUID)
2.run
3.choose the path of Xcode 7.2 beta
4.click the done button
5.restart Xcode 7.2 beta
It will work fine with Xcode 7.2 beta.
 [AutoAddUUID](https://github.com/keepyounger/AutoAddUUID) can solve the issue that any plugin doesn't work in the latest version of Xcode(include beta version).

**Comment by solszl** [comment]
well done!

**Comment by LeonidKokhnovich** [comment]
The AutoAddUUID util doesn't help on Xcode Version 7.2 (7C68). Any suggestion how to fix the issue?

**Comment by keepyounger** [comment]
@LeonidKokhnovich  This plug-in has an error #13 after I merged commit 6036d82 #12.  You can try the latest version.  Please list your steps that how do you use AutoAddUUID, if the latest version does't help.

**Comment by LeonidKokhnovich** [comment]
@keepyounger It works now. Thank you!

**Comment by mattkorp-zz** [comment]
@keepyounger thanks
