### ISSUE TITLE
可不可以同时高亮多个字符串，为不同的字符串设置不同的颜色？

### ISSUE THREAD

**Issue by zyqhi** [keepyounger/HighlightSelectedString#14]
有时候跟踪多个变量的变化时，有高亮多个符号的需求，能否实现？

**Comment by keepyounger** [comment]
这个插件只是简单的高亮行为，如果你需要更复杂的操作，你可以用这个插件[XcodeBoost](https://github.com/fortinmike/XcodeBoost)

**Comment by zyqhi** [comment]
好的，已经实现，谢谢！！

**Comment by keepyounger** [comment]
不客气
