### ISSUE TITLE
Highlight only when text is selected

### ISSUE THREAD

**Issue by vladimirvrabel** [keepyounger/HighlightSelectedString#16]
Hi, 

your plugin is almost perfect ... but you are highlight code symbols even if I do not have any text selected, only text cursor is in text editor. 

Please fix it or make some option which will highlight more symbols only when this symbol is selected. 

xCode 7.2.1
swift project

**Comment by keepyounger** [comment]
You can have a try to disable "Only Highlight Symbols".

**Comment by vladimirvrabel** [comment]
:) I was tried, but then it will match a strings, not the symbol and that is not so good :)

**Comment by keepyounger** [comment]
I  refactored  my code, and added a lot of new features (of course including you mentioned).

**Comment by vladimirvrabel** [comment]
THUMBS UP man, thank you very much, you make my life a little easier. If you want a life a much more easier, then will try AppCode for developing objective-c apps. I have to switch to xCode for swift development, because it takes some time while appCode will be perfect with swift code too ....
