### ISSUE TITLE
已选中文字无法重新获取焦点

### ISSUE THREAD

**Issue by iwill** [keepyounger/HighlightSelectedString#8]
1、选中一段文字；
2、焦点离开 —— 比如点击 Debug 区域；
3、重新点击选中文字；
期望：点击处光标闪烁；
结果：没任何反应，需要点击其它地方再点回来才行；
另外，我同时装了 Backlight 不知是否会有影响。

**Comment by keepyounger** [comment]
我按你的步骤测试了，并没有发现这个issue，如果你不确定这个问题是怎么出现的，请禁用Backlight试试

**Comment by iwill** [comment]
我又试了一下，应该是 Backlight 的问题，非常抱歉！

**Comment by iwill** [comment]
不过 HighlightSelectedString 会导致 Backlight 在这样的情况下出无法高亮背景 —— 聚焦一行时高亮一下、然后立即消失；
<img width="296" alt="screen shot 2015-09-07 at 11 05 27" src="https://cloud.githubusercontent.com/assets/188828/9708806/e918f9c4-5553-11e5-8b98-aacd57d89e60.png">

**Comment by keepyounger** [comment]
@iwill  确实存在这个问题，但是我暂时没有想到解决方案，等我想到了，再通知你

**Comment by iwill** [comment]
加油 :+1:

**Comment by keepyounger** [comment]
@iwill 我已经修复这个问题了，你更新一下试试

**Comment by keepyounger** [comment]
@iwill 对了 最好不要让这两个插件的颜色 完全一样

**Comment by iwill** [comment]
嗯 不一样 一样的话看着也晕

**Comment by iwill** [comment]
使用 Alcatraz 能更新么？

**Comment by keepyounger** [comment]
能，先remove一下 再install， 如果实还是不行， 就下载一下这个工程 build 一下

**Comment by iwill** [comment]
基本好了，但是还有一点问题：
1、选中一个单词，这时当前行背景高亮、选中字符串高亮；
2、点击另外一行（或者用方向键移动光标到另一行），这行不会高亮 —— 再点一下才能高亮；

**Comment by keepyounger** [comment]
我这好像没你说的那个问题  或许是执行顺序不同 照成的 。 想要完美解决，可以把 那个高亮光标所在行的插件功能 添加到我这个插件里面

**Comment by iwill** [comment]
那还是算了吧，已经很好了 :+1:
