### ISSUE TITLE
Doesn't work with Xcode 7 GM

### ISSUE THREAD

**Issue by MarcVienna** [keepyounger/HighlightSelectedString#9]
Doesn't work with Xcode 7 GM (7a218) 
Doesn't work with Xcode 7.1 beta (7b60)

I have 3 Xcode versions now: 6.4, 7 GM, 7.1beta. It only works in 6.4, and did work in 7beta6 - but no longer in the newer 7 GM and 7.1beta versions.

**Comment by keepyounger** [comment]
I have updated it. You should download again and build it.

**Comment by fzwo** [comment]
The update does not yet seem to be available in Alcatraz, or does not work on the Xcode 7 GM. I really miss it; this is one of my favorite plugins!

**Comment by keepyounger** [comment]
@fzwo  You can remove it first, and then install it again using your Alcatraz. You also can download  it again and build it using Xcode 7 GM.

**Comment by keepyounger** [comment]
It works well on my  Xcode 7 GM.
![xcode7](https://cloud.githubusercontent.com/assets/6264752/9900144/5d1a9000-5c91-11e5-9818-6dcbe14d9992.png)

**Comment by keepyounger** [comment]
You should click Load Bundles when you see the follow Alert
![loadbundles](https://cloud.githubusercontent.com/assets/6264752/9900177/917ee26a-5c91-11e5-8a80-85d07f0d4e20.png)

**Comment by fzwo** [comment]
Sorry, you're right. False alarm. After re-installing Alcatraz and re-installing your plugin, I had not restarted Xcode. Did now, everything works.

Let me take this opportunity to say thank you for this small but very helpful plugin! It really helps when reading code.

**Comment by MarcVienna** [comment]
I can confirm it works with Xcode 6.4 and also with Xcode 7.1 beta (7b60).

Thank you!

**Comment by MarcVienna** [comment]
Almost. If you directly double-click a new word, the highlight will not be applied.

Workaround:
You have to either double-click again, or start by clicking once on the new word, then double-click.

**Comment by keepyounger** [comment]
@MarcVienna  I can't find the issue you said. Do you have any other plug-in which also can change the background color?
